### ISSUE TITLE
Слова в базу

### ISSUE THREAD

**Issue by cbytensky** [vgiv/yo#2]
авиаперелёт
видеоотчёт
вовлечённость
даймё
довернёмся
живодёрный
звёздчатый
котёнкам
крысёныш
Мальстрём
мимолётнее
Настёна
Настёнки
непричёсан
непроизнесённый
опёршись
опошлённый
осуществлённость
отчётливейший*
перещёлкнуться
поглощённость
полведёрка
преподчтёт
прибёг
пуганёшь
пятирублёвик
разлётный
свежеприобрётенный
свёрточный
сгинёт
сотрёшься
супернадёжн*
сшибёмся
твёрдокаменных
твёрдотельный
телегипнотизёр
тёмноглазой
термобельё
трёхактовый*
туфлёй
удалёнщик
холёно-*
четырёхзвёздный
энергоёмко

**Comment by cbytensky** [comment]
Это слова, которые я встретил в ёфицируемых текстах, проверил по базе версии 1.49.

**Comment by vgiv** [comment]
Большинство слов добавлено в yox.dat v.1.502
